# Generated by Django 3.2 on 2021-04-26 07:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mse_score', models.FloatField()),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('forecast_length', models.IntegerField()),
                ('target_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
